const vietnameseMessages: Record<string, string> = {
  "Unauthorized": "Chưa xác thực. Vui lòng đăng nhập.",
  "Unauthorized access": "Bạn không có quyền truy cập.",
  "Forbidden": "Bạn không có quyền thực hiện thao tác này.",
  "Not found": "Không tìm thấy dữ liệu yêu cầu.",
  "Not Found": "Không tìm thấy dữ liệu yêu cầu.",
  "Internal server error": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Internal Server Error": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "An unexpected error occurred.": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Invalid input": "Dữ liệu gửi lên không hợp lệ.",
  "Invalid credentials": "Tên đăng nhập hoặc mật khẩu không đúng.",
  "Access denied": "Bạn không có quyền thực hiện thao tác này.",
  "User not found": "Không tìm thấy người dùng.",
  "Student not found": "Không tìm thấy sinh viên.",
  "Lecturer not found": "Không tìm thấy giảng viên.",
  "Company not found": "Không tìm thấy doanh nghiệp.",
  "Department not found": "Không tìm thấy khoa.",
  "Semester not found": "Không tìm thấy học kỳ.",
  "Internship not found": "Không tìm thấy đợt thực tập.",
  "Weekly report not found": "Không tìm thấy báo cáo tuần.",
  "Submission not found": "Không tìm thấy bài nộp.",
  "Evaluation not found": "Không tìm thấy đánh giá.",
  "Document not found": "Không tìm thấy tài liệu.",
  "Notification not found": "Không tìm thấy thông báo.",
  "Feedback not found": "Không tìm thấy phản hồi.",
  "Assignment not found": "Không tìm thấy phân công.",
  "Account request not found": "Không tìm thấy yêu cầu tài khoản.",
  "No active semester found for assignment": "Không có học kỳ đang hoạt động.",
  "No worksheet found in Excel file": "Tệp Excel không có trang tính nào.",
  "Current password is invalid": "Mật khẩu hiện tại không đúng.",
  "Invalid or expired reset token": "Liên kết đặt lại mật khẩu không hợp lệ hoặc đã hết hạn.",
  "Refresh token has expired": "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
  "One or more submissions were not found": "Không tìm thấy một hoặc nhiều bài nộp.",
  "Error retrieving evaluations": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error filtering evaluations": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error retrieving evaluation": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error retrieving evaluation scores": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error creating evaluation": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error updating evaluation": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error finalizing evaluation": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error deleting evaluation": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error getting average grade": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error checking evaluation": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "Error getting statistics": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
};

export function toVietnameseMessage(message: string): string {
  return vietnameseMessages[message] ?? message;
}